# Generated by Django 4.2.5 on 2023-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_urls_short_name_alter_urls_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='urls',
            name='name',
            field=models.CharField(help_text='Максимальная длина ссылки - 400 символов', max_length=400, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_name',
            field=models.SlugField(error_messages={'unique': 'Такая ссылка уже существует'}, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
